base_url = "https://mabuya.vercel.app/"
title = "运指如飞"
description = "〠 一个古董程序员的琐碎记事."
author = "Arvin"

compile_sass = true
generate_feeds = true
feed_filenames = ["rss.xml", "atom.xml"]
minify_html = true
build_search_index = false
taxonomies = [{ name = "tags", feed = true }]

[markdown]
highlight_code = true
highlight_theme = "visual-studio-dark"
# More syntax highlighting themes: https://www.getzola.org/documentation/getting-started/configuration/#syntax-highlighting
smart_punctuation = true

[extra]
author = "Arvin"
email = "arvincheng888@gmail.com"
github = "https://github.com/redwood9"
timeformat = "%B %e, %Y"                   # e.g. June 14, 2021

[[extra.menu]]
name = "Archive"
url = "/"

[[extra.menu]]
name = "Tags"
url = "tags"

[extra.footer]
info = 'Powered by <a href="https://www.getzola.org" target="_blank">Zola</a>.'
